apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-test
  namespace: default
  labels:
    app: nest-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-test
  template:
    metadata:
      labels:
        app: nest-test
    spec:
      containers:
        - name: nest-test
          image: nest-test
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
